---
name: Tests

on:
  workflow_call:
  pull_request:

jobs:
  unittests:
    strategy:
      matrix:
        platform: ["platform=macOS"]
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Test Swift Framework
        run: xcodebuild -project redblacktree.xcodeproj
                        -scheme redblacktree test
                        -destination "${{ matrix.platform }}"